pref("extensions.clrtabs.fadedeg", 1);
pref("extensions.clrtabs.scheme", 1);
pref("extensions.clrtabs.menu", true);
pref("extensions.clrtabs.firstrun", "0");
pref("extensions.clrtabs.advanced", false);
pref("extensions.clrtabs.satmin", 22);
pref("extensions.clrtabs.satmax", 100);
pref("extensions.clrtabs.lummin", 68);
pref("extensions.clrtabs.lummax", 78);
pref("extensions.clrtabs.sat", 61);
pref("extensions.clrtabs.lum", 73);
pref("extensions.clrtabs.bgpic", false);
pref("extensions.clrtabs.bgpicpath", "chrome://clrtabs/content/ctbg.gif");
pref("extensions.clrtabs.dpref", "binaryturf.com~#9cc8ff`apnphotographyschool.com~rgb(229, 224, 195)`about:blank~rgb(255, 218, 117)");
pref("extensions.clrtabs.enabledomain", true);
pref("extensions.clrtabs.colorunmatcheddomain", true);
pref("extensions.clrtabs.txtreverse", false);
pref("extensions.clrtabs.standout", false);
pref("extensions.clrtabs.clrAllTabsPopPref",true);
pref("extensions.clrtabs.txtshadow",true);
pref("extensions.clrtabs.aggressive",true);
pref("extensions.clrtabs.currenttab",false);
pref("extensions.clrtabs.dispstack",true);
pref("extensions.clrtabs.tablabelblink",false);
pref("extensions.clrtabs.currenttabclr","#FFE57D");
pref("extensions.clrtabs.tabtextclr","#000000");
pref("extensions.clrtabs.uncoloredbgclr","#EEEEEE");
pref("extensions.clrtabs.consolelog",false);
pref("extensions.clrtabs.minify",false);